services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml
    volumes:
      - ./jenkins.yaml:/var/jenkins_home/jenkins.yaml
    restart: unless-stopped

